// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dummy/v1/dummy.proto

package dummyv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EchoMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EchoMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EchoMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EchoMessageMultiError, or
// nil if none found.
func (m *EchoMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *EchoMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_EchoMessage_Value_Pattern.MatchString(m.GetValue()) {
		err := EchoMessageValidationError{
			field:  "Value",
			reason: "value does not match regex pattern \"^[^:#@\\\\s]{1,254}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return EchoMessageMultiError(errors)
	}

	return nil
}

// EchoMessageMultiError is an error wrapping multiple validation errors
// returned by EchoMessage.ValidateAll() if the designated constraints aren't met.
type EchoMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EchoMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EchoMessageMultiError) AllErrors() []error { return m }

// EchoMessageValidationError is the validation error returned by
// EchoMessage.Validate if the designated constraints aren't met.
type EchoMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EchoMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EchoMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EchoMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EchoMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EchoMessageValidationError) ErrorName() string { return "EchoMessageValidationError" }

// Error satisfies the builtin error interface
func (e EchoMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEchoMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EchoMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EchoMessageValidationError{}

var _EchoMessage_Value_Pattern = regexp.MustCompile("^[^:#@\\s]{1,254}$")
